### ISSUE TITLE
scripts/auth_hosts

### ISSUE THREAD

**Issue by criztovyl** [debugish/env#1]
Hey @deshawnbw,
would you allow me to include your [auth_hosts](https://github.com/deshawnbw/env/blob/master/scripts/auth_hosts) script (in a more general version :) ) into projects of me?

You gave no license, that's why I ask :)

Thank you.

**Comment by deshawnbw** [comment]
Hola, thanks for checking and don't feel bad for using it if you were waiting for a response :)

... thanks for pointing out the lack of a license on this repo, will add a WTFPL when i'm not lazy
